const en = {
  translation: {
    common: {
      productDescription: 'OpenList and local media scraping workbench',
      save: 'Save', cancel: 'Cancel', close: 'Close', edit: 'Edit', remove: 'Delete', test: 'Test', refresh: 'Refresh',
      enabled: 'Enabled', disabled: 'Disabled', healthy: 'Healthy', untested: 'Untested', failed: 'Failed', loading: 'Loading…',
    },
    language: { label: 'Language', auto: 'Auto', english: 'English', chinese: '简体中文' },
    theme: { dark: 'Use dark theme', light: 'Use light theme' },
    navigation: {
      aria: 'Application navigation', open: 'Open navigation', close: 'Close navigation', skip: 'Skip to content', logout: 'Log out',
      primary: 'Workspace', administration: 'Administration', overview: 'Overview', connections: 'OpenList connections', targets: 'Scrape targets', jobs: 'Scrape jobs', settings: 'Scraping settings', logs: 'Logs', profile: 'Profile', administrator: 'Administrator',
    },
    auth: {
      login: { title: 'Welcome back', description: 'Sign in to manage OpenList scraping', username: 'Username', password: 'Password', submit: 'Sign in', submitting: 'Signing in…', hint: 'First start: use admin / admin, then set permanent credentials.', failed: 'Sign-in failed' },
      setup: { title: 'Secure the administrator account', description: 'Replace the one-time admin/admin credentials before continuing.', username: 'Administrator username', password: 'New password', confirm: 'Confirm password', submit: 'Complete setup', mismatch: 'Passwords do not match', failed: 'Administrator setup failed' },
    },
    dashboard: {
      eyebrow: 'Scrape with confidence', title: 'Your media, organized and enriched', description: 'Use OpenList or a local /media directory, constrain a media root, and run a read-only candidate scan. TMDB matching and execution build on the saved fingerprint.',
      connections: 'Connections', connectionsDescription: 'Configured OpenList servers', jobs: 'Scrape jobs', jobsDescription: 'Persistent execution history and progress', safety: 'Safety first', safetyDescription: 'Tokens are encrypted and never returned by the API', getStarted: 'Add your first connection',
    },
    connections: {
      title: 'OpenList connections', description: 'Connections are validated before saving. Tokens are encrypted and never shown again.', add: 'Add connection', empty: 'No OpenList connections yet.', emptyDescription: 'Add a server to begin browsing media directories.',
      name: 'Name', baseUrl: 'Base URL', token: 'Token', tokenOptional: 'New token (optional)', qps: 'File API QPS', qpm: 'File API QPM', account: 'Account', basePath: 'Account root', lastTest: 'Last test', status: 'Status', actions: 'Actions',
      createTitle: 'Add OpenList connection', editTitle: 'Edit OpenList connection', createDescription: 'Saving performs a live /api/me check.', editDescription: 'Changing the URL marks the connection untested until the next check.',
      saving: 'Saving…', testing: 'Testing…', saved: 'Connection saved', testPassed: 'Connection test passed', tokenRotated: 'Token rotated', deleted: 'Connection deleted',
      deleteConfirm: 'Delete connection “{{name}}”?', formError: 'Could not save the connection', testError: 'Connection test failed', deleteError: 'Could not delete the connection', placeholderName: 'Home media', placeholderUrl: 'http://openlist.local:5244',
    },
    targets: {
      title: 'Scrape targets', description: 'Constrain scraping to an explicit OpenList or local media root.', add: 'Add target', empty: 'No scrape targets yet.', emptyDescription: 'Create an OpenList or local directory target.',
      name: 'Name', sourceType: 'Storage source', source: { openlist: 'OpenList', local: 'Local directory' }, connection: 'OpenList connection', rootPath: 'Root path', libraryType: 'Media type', movie: 'Movie', tv: 'TV show', anime: 'Anime', rename: 'Allow media rename', renameWarning: 'Enables rename planning for this target. Execution will still require an explicit preview and confirmation.', enabled: 'Target enabled',
      createTitle: 'Add scrape target', editTitle: 'Edit scrape target', createDescription: 'The directory is read once before the target is saved.', browse: 'Browse directory', browserTitle: 'Media directory', openListBrowserTitle: 'Choose an OpenList directory', localBrowserTitle: 'Choose a local directory', choose: 'Choose', selectDirectory: 'Use this directory', localWritable: '{{root}} is writable for UID {{uid}} (groups: {{groups}}).', localReadOnly: '{{root}} is read-only for UID {{uid}} (groups: {{groups}}); scans work, but writes are disabled.', localUnreadable: 'No read access to {{root}} for UID {{uid}} (groups: {{groups}}). Set PUID/PGID or MEDIA_GID to a host identity allowed to read this directory.', localNotMounted: '{{root}} is not mounted as a directory. Check HOST_MEDIA_DIR and Docker file sharing.', currentPath: 'Current path', up: 'Up one level', noEntries: 'This directory is empty.', file: 'File', directory: 'Directory',
      scan: 'Scan media', scanning: 'Scanning…', scanTitle: 'Media scan', scanDescription: 'Read-only discovery; no media files are modified.', scanningDescription: 'Reading the target recursively and identifying media candidates…', scanStatus: 'Status', scanSucceeded: 'Completed', candidates: 'Candidates', videoFiles: 'Video files', scrapedCandidates: 'Scraped', scraped: 'Scraped', notScraped: 'Not scraped', scrapeFilter: 'Filter by scrape status', allScrapeStates: 'All media', onlyScraped: 'Scraped only', onlyUnscraped: 'Not scraped only', noCandidates: 'No media candidates were found.', noFilteredCandidates: 'No media matches this filter.', ready: 'Ready', needs_review: 'Needs review', confidence: '{{value}}% confidence', videoCount: '{{count}} video', videoCount_other: '{{count}} videos', scanError: 'Could not scan the target',
      tmdbPreview: 'TMDB preview', rescrape: 'Scrape again', searchTitle: 'Search title', searchYear: 'Year', searchTMDB: 'Search TMDB', searching: 'Searching…', noTMDBResults: 'TMDB returned no matching results.', noOverview: 'No overview is available.', selectMatch: 'Use this match', matchError: 'Could not search TMDB', previewError: 'Could not create the scrape preview', previewReady: 'Plan ready', previewBlocked: 'Blocked', readOnly: 'Read only', renamePlan: 'Rename plan', directoryCreates: 'Directories to create', directoryRenames: 'Directories to rename', fileRenames: 'Files to rename', noRenames: 'No media rename is planned.', generatedFiles: 'Generated metadata', nfoPreview: 'Preview NFO XML', previewWarnings: 'Review required', previewConflicts: 'Blocking conflicts', previewExpires: 'This immutable preview expires at {{value}}.', execute: 'Confirm and execute', submittingJob: 'Submitting…', executeError: 'Could not submit the scrape job', executeConfirm: 'Execute {{renames}} media operations and upload {{files}} metadata files? The server will stop rather than overwrite conflicting media.',
      warnings: { rename_disabled: 'Media rename is disabled for this target.', year_missing: 'TMDB did not provide a release year; execution will remain blocked.' },
      conflicts: { target_exists: 'A destination path already exists.', duplicate_target: 'Multiple source items map to the same destination.', video_missing: 'The candidate no longer contains a video file.', multiple_movie_videos: 'A movie candidate contains multiple video files and cannot be renamed safely.', season_ambiguous: 'A season directory contains conflicting season markers.', season_invalid: 'A season directory contains an invalid season marker.', duplicate_season_directory: 'Multiple directories map to the same season.', episode_unrecognized: 'A video file has no unambiguous season and episode marker.', episode_metadata_missing: 'TMDB has no matching metadata for this season and episode.' },
      saving: 'Saving…', saved: 'Target saved', deleted: 'Target deleted', deleteConfirm: 'Delete target “{{name}}”?', formError: 'Could not save the target', deleteError: 'Could not delete the target', browserError: 'Could not read the directory', placeholderName: 'Movies', placeholderPath: '/media/movies',
    },
    settings: {
      title: 'Scraping settings', description: 'Configure TMDB matching, network proxy, and optional AI-assisted media recognition. Secrets are encrypted and never returned by the API.', tmdbSection: 'TMDB', tmdbSectionDescription: 'Metadata matching and image download endpoints.', apiKey: 'TMDB API key', apiKeySaved: 'An encrypted key is saved. Leave blank to keep it unchanged.', apiKeyMissing: 'No API key is configured.', apiKeyPlaceholder: 'Enter a TMDB v3 API key', baseUrl: 'TMDB API domain', imageBaseUrl: 'TMDB image domain', domainHint: 'Choose a built-in domain or provide a custom endpoint.', customDomain: 'Custom domain', customAPIUrl: 'Custom TMDB API URL', customImageUrl: 'Custom TMDB image URL', language: 'Metadata language', languageHint: 'Use a TMDB language code such as zh-CN or en-US.', region: 'Region', regionHint: 'Optional ISO country code such as CN or US.', posterSize: 'Poster size', backdropSize: 'Backdrop size', timeout: 'Request timeout (seconds)', proxySection: 'Network proxy', proxyDescription: 'Optional HTTP proxy used for TMDB API requests and image downloads. Leave both fields blank for a direct connection.', proxyHost: 'Proxy host', proxyPort: 'Proxy port', aiSection: 'AI media recognition', aiDescription: 'When local filename parsing confidence is below 70%, use an OpenAI-compatible API and fall back safely on any failure.', aiEnabled: 'Enable AI-assisted recognition', aiEnabledHint: 'Only low-confidence candidates are sent; successful local parsing is not sent.', aiApiKey: 'AI API key', aiApiKeySaved: 'An encrypted AI key is saved. Leave blank to keep it unchanged.', aiApiKeyMissing: 'No AI API key is configured.', aiApiKeyPlaceholder: 'Enter an OpenAI-compatible API key', aiBaseUrl: 'AI API base URL', aiModel: 'Model', aiQPM: 'Requests per minute', aiTimeout: 'AI timeout (seconds)', saveError: 'Could not save scraping settings', saved: 'Scraping settings saved', testTMDB: 'Test saved TMDB configuration', testAI: 'Test saved AI configuration', testing: 'Testing…', testPassed: 'TMDB connection test passed', testError: 'TMDB connection test failed', aiTestPassed: 'AI media recognition test passed', aiTestError: 'AI media recognition test failed', saving: 'Saving…',
    },
    profile: { title: 'Profile', description: 'Current authenticated account', username: 'Username', role: 'Role' },
    jobs: {
      title: 'Scrape jobs', description: 'Persistent storage execution progress, operation checkpoints, and recoverable failures.', filter: 'Filter jobs', all: 'All statuses', empty: 'No scrape jobs yet.', loadError: 'Could not load scrape jobs', retryError: 'Could not retry the job', cancelError: 'Could not cancel the job', retry: 'Retry from checkpoint', cancel: 'Cancel pending job', jobNumber: 'Job #{{id}}', targetNumber: 'Target #{{id}}', attempts: 'Attempts', checkpoint: 'Checkpoint', preview: 'Preview', operations: 'Operations', retention: 'Retention', retentionTitle: 'Job record retention', retentionDescription: 'Completed, failed, and canceled jobs older than this period are deleted with their operation details. Active jobs are never deleted.', retentionDays: 'Keep job records for', dayCount_one: '{{count}} day', dayCount_other: '{{count}} days', saving: 'Saving…', settingsSaved: 'Job record retention saved', settingsLoadError: 'Could not load job record retention', settingsSaveError: 'Could not save job record retention',
      status: { pending: 'Pending', running: 'Running', succeeded: 'Succeeded', failed: 'Failed', canceled: 'Canceled' },
      stage: { preparing: 'Preparing', renaming: 'Renaming', generating: 'Generating', uploading: 'Uploading', verifying: 'Verifying', marking: 'Writing marker', completed: 'Completed' },
      operationStatus: { pending: 'Pending', running: 'Running', succeeded: 'Succeeded', skipped: 'Already applied', failed: 'Failed' },
    },
    logs: { description: 'Search API requests, application events, and administrator audit records.', tabs: { api: 'API', application: 'Application', audit: 'Audit' }, search: 'Search logs', export: 'Export CSV', loadError: 'Could not load logs', empty: 'No matching logs.', time: 'Time', type: 'Type', summary: 'Summary', context: 'Context', fields: 'Structured fields', total: '{{count}} records', retention: 'Retention', retentionTitle: 'Log retention', retentionDescription: 'Expired API, application, and audit logs are deleted at startup, after saving, and automatically every six hours.', retentionDays: 'Keep logs for', dayCount_one: '{{count}} day', dayCount_other: '{{count}} days', saving: 'Saving…', settingsSaved: 'Log retention saved', settingsLoadError: 'Could not load log retention', settingsSaveError: 'Could not save log retention', clear: 'Clear logs', clearTitle: 'Clear logs manually', clearDescription: 'Permanently delete the selected log category. This action cannot be undone.', clearScope: 'Logs to clear', clearTypes: { api: 'API logs', application: 'Application logs', audit: 'Audit logs', all: 'All logs' }, auditClearNotice: 'A new audit record of this clear action will remain after audit logs are deleted.', confirmClear: 'Clear permanently', clearing: 'Clearing…', cleared: 'Deleted {{count}} log records', clearError: 'Could not clear logs' },
    errors: {
      invalidResponse: 'The server returned an invalid response.', requestFailed: 'Request failed.',
      codes: {
        auth: { invalid_credentials: 'Invalid username or password.', token_missing: 'Please sign in.', token_invalid: 'Your session is invalid or expired.', token_revoked: 'Your session has ended. Please sign in again.', setup_required: 'Complete administrator setup first.', admin_required: 'Administrator permission is required.' },
        connection: { not_found: 'OpenList connection not found.', invalid_id: 'Connection ID is invalid.', job_active: 'Wait for active jobs before changing this connection.' },
        target: { not_found: 'Scrape target not found.', invalid_id: 'Target ID is invalid.', invalid_path: 'Storage path is invalid.', invalid_library_type: 'The media type is invalid.', invalid_source_type: 'The storage source is invalid.', connection_required: 'Choose an OpenList connection.', local_root_overlap: 'This local root overlaps another enabled target.', path_outside_root: 'The path is outside the scrape target root.', path_outside_account: 'The path is outside the OpenList account root.', connection_disabled: 'The OpenList connection is disabled.', job_active: 'Wait for active jobs before changing this target.' },
        scan: { not_found: 'Directory scan not found.', invalid_id: 'Scan ID is invalid.', target_disabled: 'The scrape target is disabled.', already_running: 'A scan is already running for this target.', too_large: 'The directory contains too many entries for one safe scan.', too_deep: 'The directory exceeds the safe scan depth.', path_outside_candidate: 'OpenList returned an entry outside the candidate root.', canceled: 'The directory scan was canceled.' },
        candidate: { not_found: 'Media candidate not found.', source_missing: 'The media candidate no longer exists.', path_outside_root: 'The candidate is outside the target root.' },
        preview: { not_found: 'Scrape preview not found.', invalid_id: 'Preview ID is invalid.', invalid_snapshot: 'The stored preview snapshot is invalid.', stale: 'The directory changed after scanning. Run a new scan.', expired: 'The scrape preview expired. Create a new preview.' },
        job: { not_found: 'Scrape job not found.', invalid_id: 'Job ID is invalid.', queue_full: 'The scrape queue is full. Try again later.', already_active: 'This target or media already has an active job.', fingerprint_mismatch: 'The confirmed fingerprint does not match the preview.', preview_blocked: 'The preview has blocking conflicts.', rename_confirmation_required: 'Explicitly confirm media rename.', not_retryable: 'Only failed jobs can be retried.', not_cancelable: 'Only pending jobs can be canceled.', target_exists: 'A destination appeared after preview.', source_missing: 'A source media path is missing.', source_changed: 'The target source changed after submission.', verification_failed: 'Final storage verification failed.', marker_verification_failed: 'The scrape marker could not be verified.', image_download_failed: 'Could not download a TMDB image.', invalid_image_type: 'TMDB returned an unsupported image type.', image_too_large: 'A TMDB image exceeds the size limit.', interrupted: 'The job was interrupted; retry from its checkpoint.', invalid_retention_days: 'Choose a job record retention period from 1 to 30 days.', settings_load_failed: 'Could not load job record settings.', settings_save_failed: 'Could not save job record settings.', settings_invalid: 'The saved job record retention setting is invalid.', cleanup_failed: 'Could not apply job record retention.', audit_failed: 'Could not record the job retention change.' },
        local: { invalid_path: 'The local media path is invalid.', path_outside_root: 'Local paths must remain below /media.', not_mounted: 'The /media directory is not mounted. Check HOST_MEDIA_DIR.', not_directory: 'The selected local path is not a directory.', path_unavailable: 'The directory does not exist. Please select a directory again.', permission_denied: 'The container identity cannot access this path. Match PUID/PGID or MEDIA_GID to the host permissions.', symlink_unsupported: 'Symbolic links are not supported in local targets.', cross_device_move: 'Moving media across filesystems is not supported.', read_failed: 'Could not read the local directory.', stat_failed: 'Could not inspect the local path.', mkdir_failed: 'Could not create the local directory.', rename_failed: 'Could not rename the local path.', write_failed: 'Could not write local metadata.' },
        tmdb: { not_configured: 'Configure a TMDB API key first.', invalid_query: 'Enter a search title.', invalid_id: 'TMDB ID is invalid.', invalid_url: 'TMDB API URL is invalid.', invalid_image_url: 'TMDB image URL is invalid.', invalid_language: 'TMDB language code is invalid.', invalid_region: 'TMDB region code is invalid.', invalid_image_size: 'TMDB image size is invalid.', invalid_proxy: 'Configure both a valid proxy host and port.', proxy_failed: 'Could not use the configured proxy.', authentication_failed: 'TMDB API key is invalid.', connection_failed: 'Could not connect to TMDB.', timeout: 'TMDB request timed out.', rate_limited: 'TMDB rate limit was exceeded.', not_found: 'TMDB item was not found.', no_results: 'TMDB returned no matching results.', invalid_response: 'TMDB returned an invalid response.', http_error: 'TMDB returned an HTTP error.' },
        ai: { not_configured: 'Enable AI recognition and configure an API key first.', disabled: 'AI media recognition is disabled.', invalid_url: 'AI API URL is invalid.', invalid_model: 'AI model is invalid.', invalid_qpm: 'AI request limit is invalid.', invalid_timeout: 'AI timeout is invalid.', authentication_failed: 'AI API key is invalid.', connection_failed: 'Could not connect to the AI service.', timeout: 'AI request timed out.', rate_limited: 'AI rate limit was exceeded.', invalid_response: 'AI returned an invalid response.', http_error: 'AI service returned an HTTP error.', unavailable: 'AI media recognition is unavailable.' },
        openlist: { invalid_url: 'OpenList URL is invalid.', invalid_scheme: 'Use an HTTP or HTTPS OpenList URL.', dns_failed: 'OpenList host could not be resolved.', blocked_address: 'This network address is blocked.', connection_failed: 'Could not connect to OpenList.', authentication_failed: 'The OpenList token is invalid or lacks permission.', account_disabled: 'The OpenList account is disabled.', invalid_response: 'OpenList returned an invalid response.', api_error: 'OpenList rejected the request.', http_error: 'OpenList returned an HTTP error.' },
        logs: { invalid_retention_days: 'Choose a log retention period from 1 to 30 days.', invalid_type: 'The selected log category is invalid.', settings_load_failed: 'Could not load log settings.', settings_save_failed: 'Could not save log settings.', settings_invalid: 'The saved log retention setting is invalid.', clear_failed: 'Could not delete logs.', audit_failed: 'Could not record the log management action.' },
      },
    },
  },
}

const zhCN = {
  translation: {
    common: {
      productDescription: 'OpenList 与本地媒体目录刮削工作台',
      save: '保存', cancel: '取消', close: '关闭', edit: '编辑', remove: '删除', test: '测试', refresh: '刷新',
      enabled: '已启用', disabled: '已停用', healthy: '正常', untested: '未测试', failed: '失败', loading: '加载中…',
    },
    language: { label: '语言', auto: '自动', english: 'English', chinese: '简体中文' },
    theme: { dark: '切换到深色主题', light: '切换到浅色主题' },
    navigation: {
      aria: '应用导航', open: '打开导航', close: '关闭导航', skip: '跳到主要内容', logout: '退出登录',
      primary: '工作台', administration: '管理', overview: '概览', connections: 'OpenList 连接', targets: '刮削目标', jobs: '刮削作业', settings: '刮削设置', logs: '日志', profile: '个人资料', administrator: '管理员',
    },
    auth: {
      login: { title: '欢迎回来', description: '登录后管理 OpenList 刮削', username: '用户名', password: '密码', submit: '登录', submitting: '登录中…', hint: '首次启动请使用 admin / admin，随后设置正式凭据。', failed: '登录失败' },
      setup: { title: '保护管理员账户', description: '继续使用前，请替换一次性 admin/admin 凭据。', username: '管理员用户名', password: '新密码', confirm: '确认密码', submit: '完成初始化', mismatch: '两次输入的密码不一致', failed: '管理员初始化失败' },
    },
    dashboard: {
      eyebrow: '安心刮削', title: '整理并丰富你的媒体目录', description: '使用 OpenList 或挂载到 /media 的本地目录，约束媒体根目录并执行只读扫描；后续 TMDB 匹配与执行基于已保存的目录指纹。',
      connections: '连接', connectionsDescription: '已配置的 OpenList 服务器', jobs: '刮削作业', jobsDescription: '持久化执行历史和进度', safety: '安全优先', safetyDescription: 'Token 加密保存且 API 永不返回明文', getStarted: '添加第一个连接',
    },
    connections: {
      title: 'OpenList 连接', description: '连接保存前会自动验证，Token 加密保存且不会再次显示。', add: '添加连接', empty: '还没有 OpenList 连接。', emptyDescription: '添加服务器后即可开始浏览媒体目录。',
      name: '名称', baseUrl: 'Base URL', token: 'Token', tokenOptional: '新 Token（可选）', qps: '文件 API QPS', qpm: '文件 API QPM', account: '账号', basePath: '账号根目录', lastTest: '最近测试', status: '状态', actions: '操作',
      createTitle: '添加 OpenList 连接', editTitle: '编辑 OpenList 连接', createDescription: '保存时会实时调用 /api/me 验证。', editDescription: '修改 URL 后会标记为未测试，直到下次检查。',
      saving: '保存中…', testing: '测试中…', saved: '连接已保存', testPassed: '连接测试通过', tokenRotated: 'Token 已更新', deleted: '连接已删除',
      deleteConfirm: '确定删除连接“{{name}}”吗？', formError: '保存连接失败', testError: '连接测试失败', deleteError: '删除连接失败', placeholderName: '家庭媒体', placeholderUrl: 'http://openlist.local:5244',
    },
    targets: {
      title: '刮削目标', description: '用明确的 OpenList 或本地媒体根目录约束刮削范围。', add: '添加目标', empty: '还没有刮削目标。', emptyDescription: '创建 OpenList 或本地目录刮削目标。',
      name: '名称', sourceType: '存储来源', source: { openlist: 'OpenList', local: '本地目录' }, connection: 'OpenList 连接', rootPath: '根目录', libraryType: '媒体类型', movie: '电影', tv: '电视剧', anime: '动画', rename: '允许媒体重命名', renameWarning: '为该目标启用重命名计划；实际执行仍需经过明确预览和确认。', enabled: '启用目标',
      createTitle: '添加刮削目标', editTitle: '编辑刮削目标', createDescription: '保存前会读取一次目标目录进行验证。', browse: '浏览目录', browserTitle: '媒体目录', openListBrowserTitle: '选择 OpenList 目录', localBrowserTitle: '选择本地目录', choose: '选择', selectDirectory: '使用此目录', localWritable: '{{root}} 对 UID {{uid}}（组：{{groups}}）可写。', localReadOnly: '{{root}} 对 UID {{uid}}（组：{{groups}}）只读；可以扫描，但不能写入。', localUnreadable: 'UID {{uid}}（组：{{groups}}）没有读取 {{root}} 的权限。请将 PUID/PGID 或 MEDIA_GID 设置为宿主机上有权访问该目录的用户或组。', localNotMounted: '{{root}} 未挂载为目录，请检查 HOST_MEDIA_DIR 与 Docker 文件共享。', currentPath: '当前路径', up: '返回上一级', noEntries: '该目录为空。', file: '文件', directory: '目录',
      scan: '扫描媒体', scanning: '扫描中…', scanTitle: '媒体扫描', scanDescription: '仅进行只读发现，不会修改媒体文件。', scanningDescription: '正在递归读取目标目录并识别媒体候选…', scanStatus: '状态', scanSucceeded: '已完成', candidates: '候选', videoFiles: '视频文件', scrapedCandidates: '已刮削', scraped: '已刮削', notScraped: '未刮削', scrapeFilter: '按刮削状态筛选', allScrapeStates: '全部媒体', onlyScraped: '仅已刮削', onlyUnscraped: '仅未刮削', noCandidates: '未发现媒体候选。', noFilteredCandidates: '当前筛选条件下没有媒体。', ready: '可预览', needs_review: '需要检查', confidence: '置信度 {{value}}%', videoCount: '{{count}} 个视频', videoCount_other: '{{count}} 个视频', scanError: '扫描目标失败',
      tmdbPreview: 'TMDB 预览', rescrape: '重新刮削', searchTitle: '搜索标题', searchYear: '年份', searchTMDB: '搜索 TMDB', searching: '搜索中…', noTMDBResults: 'TMDB 未返回匹配结果。', noOverview: '暂无简介。', selectMatch: '使用该匹配', matchError: '搜索 TMDB 失败', previewError: '创建刮削预览失败', previewReady: '计划就绪', previewBlocked: '存在阻断', readOnly: '只读', renamePlan: '重命名计划', directoryCreates: '将创建的目录', directoryRenames: '将重命名的目录', fileRenames: '将重命名的文件', noRenames: '不会重命名媒体。', generatedFiles: '将生成的元数据', nfoPreview: '预览 NFO XML', previewWarnings: '需要确认', previewConflicts: '阻断冲突', previewExpires: '该不可变预览将在 {{value}} 过期。', execute: '确认并执行', submittingJob: '提交中…', executeError: '提交刮削作业失败', executeConfirm: '将执行 {{renames}} 项媒体操作并上传 {{files}} 个元数据文件。若发现媒体冲突，服务端会停止而不是覆盖，是否继续？',
      warnings: { rename_disabled: '该目标未启用媒体重命名。', year_missing: 'TMDB 未提供发行年份，执行将保持禁用。' },
      conflicts: { target_exists: '目标路径已经存在。', duplicate_target: '多个源项目映射到了同一个目标。', video_missing: '候选中已没有视频文件。', multiple_movie_videos: '电影候选包含多个视频，无法安全自动重命名。', season_ambiguous: '季目录中包含互相冲突的季号。', season_invalid: '季目录中包含无效季号。', duplicate_season_directory: '多个目录将映射到同一季目录。', episode_unrecognized: '视频文件缺少明确的季集标记。', episode_metadata_missing: 'TMDB 中没有匹配的季集元数据。' },
      saving: '保存中…', saved: '目标已保存', deleted: '目标已删除', deleteConfirm: '确定删除目标“{{name}}”吗？', formError: '保存目标失败', deleteError: '删除目标失败', browserError: '读取目录失败', placeholderName: '电影库', placeholderPath: '/media/movies',
    },
    settings: {
      title: '刮削设置', description: '配置 TMDB 匹配、网络代理与可选的 AI 辅助识别；密钥加密保存且 API 永不返回明文。', tmdbSection: 'TMDB', tmdbSectionDescription: '配置元数据匹配与图片下载地址。', apiKey: 'TMDB API Key', apiKeySaved: '已保存加密密钥，留空可保持不变。', apiKeyMissing: '尚未配置 API Key。', apiKeyPlaceholder: '输入 TMDB v3 API Key', baseUrl: 'TMDB API 域名', imageBaseUrl: 'TMDB 图片域名', domainHint: '选择内置域名，也可以填写自定义地址。', customDomain: '自定义域名', customAPIUrl: '自定义 TMDB API 地址', customImageUrl: '自定义 TMDB 图片地址', language: '元数据语言', languageHint: '使用 zh-CN、en-US 等 TMDB 语言代码。', region: '地区', regionHint: '可选 ISO 国家代码，例如 CN 或 US。', posterSize: '海报尺寸', backdropSize: '背景图尺寸', timeout: '请求超时（秒）', proxySection: '网络代理', proxyDescription: '可选 HTTP 代理，同时用于 TMDB API 请求和图片下载；主机与端口都留空时直连。', proxyHost: '代理主机', proxyPort: '代理端口', aiSection: 'AI 媒体识别', aiDescription: '本地文件名解析置信度低于 70% 时调用 OpenAI 兼容接口；任何失败都会安全回退到本地结果。', aiEnabled: '启用 AI 辅助识别', aiEnabledHint: '只发送低置信度候选；本地已成功识别的媒体不会发送。', aiApiKey: 'AI API Key', aiApiKeySaved: '已保存加密 AI 密钥，留空可保持不变。', aiApiKeyMissing: '尚未配置 AI API Key。', aiApiKeyPlaceholder: '输入 OpenAI 兼容 API Key', aiBaseUrl: 'AI API 基础地址', aiModel: '模型', aiQPM: '每分钟请求数', aiTimeout: 'AI 请求超时（秒）', saveError: '保存刮削设置失败', saved: '刮削设置已保存', testTMDB: '测试已保存的 TMDB 配置', testAI: '测试已保存的 AI 配置', testing: '测试中…', testPassed: 'TMDB 连接测试通过', testError: 'TMDB 连接测试失败', aiTestPassed: 'AI 媒体识别测试通过', aiTestError: 'AI 媒体识别测试失败', saving: '保存中…',
    },
    profile: { title: '个人资料', description: '当前登录账户', username: '用户名', role: '角色' },
    jobs: {
      title: '刮削作业', description: '查看持久化存储执行进度、操作检查点和可恢复失败。', filter: '筛选作业', all: '全部状态', empty: '还没有刮削作业。', loadError: '加载作业失败', retryError: '重试作业失败', cancelError: '取消作业失败', retry: '从检查点重试', cancel: '取消待执行作业', jobNumber: '作业 #{{id}}', targetNumber: '目标 #{{id}}', attempts: '尝试次数', checkpoint: '检查点', preview: '预览', operations: '操作明细', retention: '保留设置', retentionTitle: '作业记录保留时间', retentionDescription: '超过保留时间的成功、失败和已取消作业会连同操作明细一起删除；等待中和运行中的作业不会删除。', retentionDays: '作业记录保留时长', dayCount_one: '{{count}} 天', dayCount_other: '{{count}} 天', saving: '保存中…', settingsSaved: '作业记录保留设置已保存', settingsLoadError: '加载作业记录保留设置失败', settingsSaveError: '保存作业记录保留设置失败',
      status: { pending: '等待中', running: '执行中', succeeded: '已成功', failed: '已失败', canceled: '已取消' },
      stage: { preparing: '准备', renaming: '重命名', generating: '生成元数据', uploading: '上传', verifying: '校验', marking: '写入标记', completed: '已完成' },
      operationStatus: { pending: '等待中', running: '执行中', succeeded: '已成功', skipped: '已应用', failed: '已失败' },
    },
    logs: { description: '搜索 API 请求、应用事件和管理员审计记录。', tabs: { api: 'API', application: '应用', audit: '审计' }, search: '搜索日志', export: '导出 CSV', loadError: '加载日志失败', empty: '没有匹配的日志。', time: '时间', type: '类型', summary: '摘要', context: '上下文', fields: '结构化字段', total: '共 {{count}} 条记录', retention: '保留设置', retentionTitle: '日志保留时间', retentionDescription: '过期的 API、应用和审计日志会在启动、保存设置后以及每 6 小时自动清理一次。', retentionDays: '日志保留时长', dayCount_one: '{{count}} 天', dayCount_other: '{{count}} 天', saving: '保存中…', settingsSaved: '日志保留设置已保存', settingsLoadError: '加载日志保留设置失败', settingsSaveError: '保存日志保留设置失败', clear: '清空日志', clearTitle: '手动清空日志', clearDescription: '永久删除所选类别的日志，此操作无法撤销。', clearScope: '清空范围', clearTypes: { api: 'API 日志', application: '应用日志', audit: '审计日志', all: '全部日志' }, auditClearNotice: '删除审计日志后，会保留一条本次清空操作的新审计记录。', confirmClear: '永久清空', clearing: '清空中…', cleared: '已删除 {{count}} 条日志', clearError: '清空日志失败' },
    errors: {
      invalidResponse: '服务端返回了无效响应。', requestFailed: '请求失败。',
      codes: {
        auth: { invalid_credentials: '用户名或密码错误。', token_missing: '请先登录。', token_invalid: '会话无效或已过期。', token_revoked: '会话已失效，请重新登录。', setup_required: '请先完成管理员初始化。', admin_required: '需要管理员权限。' },
        connection: { not_found: 'OpenList 连接不存在。', invalid_id: '连接 ID 无效。', job_active: '请等待活动作业完成后再修改连接。' },
        target: { not_found: '刮削目标不存在。', invalid_id: '目标 ID 无效。', invalid_path: '存储路径无效。', invalid_library_type: '媒体类型无效。', invalid_source_type: '存储来源无效。', connection_required: '请选择 OpenList 连接。', local_root_overlap: '该本地根目录与另一个已启用目标重叠。', path_outside_root: '路径超出了刮削目标根目录。', path_outside_account: '路径超出了 OpenList 账号根目录。', connection_disabled: 'OpenList 连接已停用。', job_active: '请等待活动作业完成后再修改目标。' },
        scan: { not_found: '目录扫描不存在。', invalid_id: '扫描 ID 无效。', target_disabled: '刮削目标已停用。', already_running: '该目标已有扫描正在运行。', too_large: '目录条目过多，超出了单次安全扫描上限。', too_deep: '目录层级超出了安全扫描深度。', path_outside_candidate: 'OpenList 返回了候选根目录以外的条目。', canceled: '目录扫描已取消。' },
        candidate: { not_found: '媒体候选不存在。', source_missing: '媒体候选已不存在。', path_outside_root: '候选路径超出了目标根目录。' },
        preview: { not_found: '刮削预览不存在。', invalid_id: '预览 ID 无效。', invalid_snapshot: '保存的预览快照无效。', stale: '扫描后目录发生了变化，请重新扫描。', expired: '刮削预览已过期，请重新生成。' },
        job: { not_found: '刮削作业不存在。', invalid_id: '作业 ID 无效。', queue_full: '刮削队列已满，请稍后再试。', already_active: '该目标或媒体已有活动作业。', fingerprint_mismatch: '确认的目录指纹与预览不一致。', preview_blocked: '预览中存在阻断冲突。', rename_confirmation_required: '请明确确认媒体重命名。', not_retryable: '只能重试失败作业。', not_cancelable: '只能取消待执行作业。', target_exists: '预览后出现了目标冲突。', source_missing: '源媒体路径已不存在。', source_changed: '作业提交后目标来源发生了变化。', verification_failed: '存储最终校验失败。', marker_verification_failed: '无法校验刮削标记文件。', image_download_failed: '下载 TMDB 图片失败。', invalid_image_type: 'TMDB 返回了不支持的图片类型。', image_too_large: 'TMDB 图片超出大小限制。', interrupted: '作业被中断，可从检查点重试。', invalid_retention_days: '请选择 1 到 30 天的作业记录保留时间。', settings_load_failed: '加载作业记录设置失败。', settings_save_failed: '保存作业记录设置失败。', settings_invalid: '已保存的作业记录保留设置无效。', cleanup_failed: '应用作业记录保留设置失败。', audit_failed: '记录作业保留设置变更失败。' },
        local: { invalid_path: '本地媒体路径无效。', path_outside_root: '本地路径必须位于 /media 下。', not_mounted: '/media 目录尚未挂载，请检查 HOST_MEDIA_DIR。', not_directory: '选择的本地路径不是目录。', path_unavailable: '目录不存在，请重新选择目录。', permission_denied: '容器运行身份没有访问该路径的权限，请按宿主机权限配置 PUID/PGID 或 MEDIA_GID。', symlink_unsupported: '本地目标不支持符号链接。', cross_device_move: '不支持跨文件系统移动媒体。', read_failed: '读取本地目录失败。', stat_failed: '检查本地路径失败。', mkdir_failed: '创建本地目录失败。', rename_failed: '重命名本地路径失败。', write_failed: '写入本地元数据失败。' },
        tmdb: { not_configured: '请先配置 TMDB API Key。', invalid_query: '请输入搜索标题。', invalid_id: 'TMDB ID 无效。', invalid_url: 'TMDB API 地址无效。', invalid_image_url: 'TMDB 图片地址无效。', invalid_language: 'TMDB 语言代码无效。', invalid_region: 'TMDB 地区代码无效。', invalid_image_size: 'TMDB 图片尺寸无效。', invalid_proxy: '请同时填写有效的代理主机和端口。', proxy_failed: '无法使用已配置的代理。', authentication_failed: 'TMDB API Key 无效。', connection_failed: '无法连接 TMDB。', timeout: 'TMDB 请求超时。', rate_limited: '已达到 TMDB 频率限制。', not_found: 'TMDB 条目不存在。', no_results: 'TMDB 未返回匹配结果。', invalid_response: 'TMDB 返回了无效响应。', http_error: 'TMDB 返回 HTTP 错误。' },
        ai: { not_configured: '请先启用 AI 识别并配置 API Key。', disabled: 'AI 媒体识别尚未启用。', invalid_url: 'AI API 地址无效。', invalid_model: 'AI 模型无效。', invalid_qpm: 'AI 请求频率无效。', invalid_timeout: 'AI 请求超时配置无效。', authentication_failed: 'AI API Key 无效。', connection_failed: '无法连接 AI 服务。', timeout: 'AI 请求超时。', rate_limited: '已达到 AI 频率限制。', invalid_response: 'AI 返回了无效响应。', http_error: 'AI 服务返回 HTTP 错误。', unavailable: 'AI 媒体识别不可用。' },
        openlist: { invalid_url: 'OpenList 地址无效。', invalid_scheme: 'OpenList 地址必须使用 HTTP 或 HTTPS。', dns_failed: '无法解析 OpenList 主机。', blocked_address: '该网络地址已被安全策略阻止。', connection_failed: '无法连接 OpenList。', authentication_failed: 'OpenList Token 无效或权限不足。', account_disabled: 'OpenList 账号已被禁用。', invalid_response: 'OpenList 返回了无效响应。', api_error: 'OpenList 拒绝了请求。', http_error: 'OpenList 返回 HTTP 错误。' },
        logs: { invalid_retention_days: '请选择 1 到 30 天的日志保留时间。', invalid_type: '所选日志类别无效。', settings_load_failed: '加载日志设置失败。', settings_save_failed: '保存日志设置失败。', settings_invalid: '已保存的日志保留设置无效。', clear_failed: '删除日志失败。', audit_failed: '记录日志管理操作失败。' },
      },
    },
  },
}

export const resources = { en, 'zh-CN': zhCN } as const
